-- Flyway V1 — Initial production schema for Microsoft SQL Server (DB-03).
-- Generated from the authoritative JPA entity model via Hibernate 6 SQLServerDialect
-- (nationalized character data = NVARCHAR for Vietnamese Unicode). The only manual
-- correction applied: columnDefinition="TEXT" long-text columns are emitted as
-- NVARCHAR(MAX) instead of the deprecated, non-Unicode SQL Server TEXT type.
-- This schema is migration-owned; production runs with ddl-auto=validate.
-- Do NOT edit already-applied migrations; add a new V2+ file for future changes.

create table administrative_units (active bit not null, latitude float(53), level int, longitude float(53), sort_order int, created_at datetimeoffset(6), id bigint identity not null, parent_id bigint, updated_at datetimeoffset(6), type nvarchar(20) not null check (type in ('COUNTRY','PROVINCE','CITY','WARD','COMMUNE','AREA')), code nvarchar(255), full_path nvarchar(255), name nvarchar(255) not null, name_normalized nvarchar(255), old_name nvarchar(255), slug nvarchar(255) not null, primary key (id));
create table amenities (active bit not null, sort_order int, created_at datetimeoffset(6), id bigint identity not null, updated_at datetimeoffset(6), group_name nvarchar(30), description nvarchar(500), icon nvarchar(255), name nvarchar(255) not null, slug nvarchar(255) not null, primary key (id));
create table booking_check_in_audits (booking_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, partner_profile_id bigint not null, partner_user_id bigint not null, operation nvarchar(40) not null, primary key (id));
create table booking_check_out_audits (booking_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, partner_profile_id bigint not null, partner_user_id bigint not null, method nvarchar(20) not null check (method in ('QR_SCAN','MANUAL')), operation nvarchar(40) not null, primary key (id));
create table booking_modifications (new_adults int not null, new_check_in_date date not null, new_check_out_date date not null, new_children int not null, new_total_price numeric(15,2) not null, old_adults int not null, old_check_in_date date not null, old_check_out_date date not null, old_children int not null, old_total_price numeric(15,2) not null, price_difference numeric(15,2) not null, booking_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, new_rate_plan_id bigint, old_rate_plan_id bigint, new_rate_plan_name nvarchar(255), old_rate_plan_name nvarchar(255), primary key (id));
create table bookings (adults int not null, base_price numeric(15,2) not null, check_in_date date not null, check_out_date date not null, children int not null, coupon_discount_amount numeric(15,2), credit_amount_used numeric(15,2), discount_amount numeric(15,2) not null, final_price numeric(15,2) not null, gift_card_amount_used numeric(15,2), loyalty_discount_amount numeric(15,2), number_of_rooms int not null, rate_plan_adjustment_snapshot numeric(15,2), rate_plan_nightly_rate_snapshot numeric(15,2), rate_plan_price numeric(15,2), rate_plan_refundable bit, actual_check_in_at datetimeoffset(6), actual_check_out_at datetimeoffset(6), archived_at datetimeoffset(6), cancelled_at datetimeoffset(6), completed_at datetimeoffset(6), confirmed_at datetimeoffset(6), created_at datetimeoffset(6), hotel_id bigint not null, id bigint identity not null, last_status_changed_at datetimeoffset(6), loyalty_points_redeemed bigint, rate_plan_cancellation_deadline_at datetimeoffset(6), room_id bigint not null, selected_rate_plan_id bigint, updated_at datetimeoffset(6), user_id bigint not null, currency nvarchar(10) not null, rate_plan_meal_plan_type nvarchar(20) check (rate_plan_meal_plan_type in ('ROOM_ONLY','BREAKFAST','HALF_BOARD','FULL_BOARD','ALL_INCLUSIVE')), status nvarchar(20) not null check (status in ('PENDING','CONFIRMED','CHECK_IN_READY','CHECKED_IN','CHECKED_OUT','COMPLETED','CANCELLED','REFUNDED','ARCHIVED','NO_SHOW')), rate_plan_cancellation_policy_type nvarchar(30) check (rate_plan_cancellation_policy_type in ('FREE_CANCELLATION','PARTIALLY_REFUNDABLE','NON_REFUNDABLE','CUSTOM')), gift_card_reference nvarchar(32), coupon_code nvarchar(60), selected_rate_plan_code nvarchar(60), booking_code nvarchar(255), cancel_reason nvarchar(max), partner_note nvarchar(max), selected_rate_plan_name nvarchar(255), special_request nvarchar(max), primary key (id));
create table categories (active bit not null, sort_order int, created_at datetimeoffset(6), id bigint identity not null, parent_id bigint, updated_at datetimeoffset(6), cover_image_url nvarchar(500), color nvarchar(255), icon nvarchar(255), name nvarchar(255) not null, slug nvarchar(255) not null, type nvarchar(255), primary key (id));
create table conversations (booking_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, last_message_at datetimeoffset(6), partner_profile_id bigint not null, updated_at datetimeoffset(6), user_id bigint not null, status nvarchar(20) not null check (status in ('OPEN','CLOSED','ARCHIVED')), subject nvarchar(255), primary key (id));
create table coupon_definitions (active bit not null, booking_date_from date, booking_date_to date, combinable_with_promotions bit not null, combinable_with_travel_credits bit not null, current_usage_count int not null, discount_value numeric(15,2) not null, first_booking_only bit not null, max_discount_amount numeric(15,2), minimum_spend numeric(15,2), minimum_stay_nights int check (minimum_stay_nights>=1), total_usage_limit int check (total_usage_limit>=1), usage_limit_per_user int not null check (usage_limit_per_user>=1), valid_from date not null, valid_until date not null, created_at datetimeoffset(6), id bigint identity not null, target_id bigint, updated_at datetimeoffset(6), customer_segment nvarchar(20) not null check (customer_segment in ('ALL_USERS','NEW_USER','RETURNING_USER','MEMBER','HIGH_VALUE','MANUAL')), discount_type nvarchar(20) not null check (discount_type in ('PERCENTAGE','FIXED_AMOUNT')), minimum_tier nvarchar(20) check (minimum_tier in ('BRONZE','SILVER','GOLD','PLATINUM','DIAMOND')), target_type nvarchar(20) not null check (target_type in ('ALL','HOTEL','ROOM','PLACE_TYPE')), code nvarchar(60) not null, place_type nvarchar(100), description nvarchar(max), name nvarchar(255) not null, primary key (id));
create table customer_coupons (expires_at date, booking_id bigint, claimed_at datetimeoffset(6) not null, coupon_definition_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, updated_at datetimeoffset(6), used_at datetimeoffset(6), user_id bigint not null, status nvarchar(20) not null check (status in ('AVAILABLE','USED','EXPIRED','REVOKED')), primary key (id));
create table customer_memberships (active bit not null, manually_assigned bit not null, created_at datetimeoffset(6), id bigint identity not null, loyalty_account_id bigint, qualified_at datetimeoffset(6) not null, updated_at datetimeoffset(6), user_id bigint not null, valid_from datetimeoffset(6) not null, valid_until datetimeoffset(6), version bigint, current_tier nvarchar(20) not null check (current_tier in ('BRONZE','SILVER','GOLD','PLATINUM','DIAMOND')), primary key (id));
create table customer_profiles (marketing_consent bit not null, profile_completed bit not null, created_at datetimeoffset(6), id bigint identity not null, updated_at datetimeoffset(6), user_id bigint not null, accessibility_needs nvarchar(max), avatar_url nvarchar(255), dietary_preference nvarchar(255), emergency_contact_name nvarchar(255), emergency_contact_phone nvarchar(255), nationality nvarchar(255), passport_number_masked nvarchar(255), preferred_currency nvarchar(255) not null, preferred_language nvarchar(255) not null, preferred_payment_method nvarchar(255), travel_style nvarchar(255), primary key (id));
create table customer_recommendations (score int not null, clicked_at datetimeoffset(6), converted_at datetimeoffset(6), coupon_definition_id bigint, dismissed_at datetimeoffset(6), expires_at datetimeoffset(6), generated_at datetimeoffset(6) not null, hotel_id bigint, id bigint identity not null, place_id bigint, promotion_id bigint, room_id bigint, source_rule_id bigint, user_id bigint not null, recommendation_type nvarchar(20) not null check (recommendation_type in ('PLACE','HOTEL','ROOM','PROMOTION','COUPON','TRIP_IDEA')), reason_code nvarchar(40) not null check (reason_code in ('SAVED_SIMILAR_PLACE','VIEWED_SIMILAR_PLACE','BOOKED_SIMILAR_DESTINATION','MATCHED_TRAVEL_STYLE','MEMBERSHIP_EXCLUSIVE','LOYALTY_EXCLUSIVE','POPULAR_NEARBY','PRICE_PROMOTION','RETURNING_CUSTOMER','CONTINUE_PLANNING','MANUAL_RULE')), target_key nvarchar(60) not null, reason_text nvarchar(500), metadata_json nvarchar(max), primary key (id));
create table expense (amount float(53) not null, date date not null, id bigint identity not null, trip_id bigint not null, category nvarchar(255) not null, title nvarchar(255) not null, primary key (id));
create table gift_card_products (active bit not null, custom_amount_allowed bit not null, fixed_amount numeric(15,2), maximum_amount numeric(15,2), minimum_amount numeric(15,2), valid_days_after_activation int, valid_from date, valid_until date, created_at datetimeoffset(6), id bigint identity not null, updated_at datetimeoffset(6), version bigint, currency nvarchar(10) not null, product_code nvarchar(60) not null, description nvarchar(2000), name nvarchar(255) not null, primary key (id));
create table gift_card_transactions (amount numeric(15,2) not null, balance_after numeric(15,2) not null, balance_before numeric(15,2) not null, created_at datetimeoffset(6), gift_card_id bigint not null, id bigint identity not null, reference_id bigint, reference_type nvarchar(20) check (reference_type in ('BOOKING','PAYMENT','REFUND','ADMIN','CAMPAIGN','SYSTEM')), transaction_type nvarchar(20) not null check (transaction_type in ('ISSUE','ACTIVATE','REDEMPTION','REFUND','ADJUSTMENT','EXPIRATION','CANCELLATION')), description nvarchar(255) not null, idempotency_key nvarchar(255), primary key (id));
create table gift_cards (code_last4 nvarchar(4) not null, current_balance numeric(15,2) not null, original_amount numeric(15,2) not null, activated_at datetimeoffset(6), cancelled_at datetimeoffset(6), created_at datetimeoffset(6), expires_at datetimeoffset(6), fully_redeemed_at datetimeoffset(6), id bigint identity not null, issued_at datetimeoffset(6) not null, product_id bigint not null, purchaser_user_id bigint, recipient_user_id bigint, updated_at datetimeoffset(6), version bigint, currency nvarchar(10) not null, status nvarchar(20) not null check (status in ('ISSUED','ACTIVE','PARTIALLY_REDEEMED','FULLY_REDEEMED','EXPIRED','CANCELLED')), gift_card_code nvarchar(32) not null, personal_message nvarchar(500), recipient_email nvarchar(255), primary key (id));
create table hotel_details (airport_shuttle bit not null, available_rooms int check (available_rooms>=0), breakfast_included bit not null, check_in_time time not null, check_out_time time not null, distance_to_beach_meters int check (distance_to_beach_meters>=0), distance_to_city_center_meters int check (distance_to_city_center_meters>=0), free_cancellation bit not null, parking_available bit not null, parking_free bit not null, prepayment_required bit not null, star_rating int not null check ((star_rating<=5) and (star_rating>=1)), total_rooms int check (total_rooms>=0), wifi_available bit not null, wifi_free bit not null, created_at datetimeoffset(6), id bigint identity not null, place_id bigint not null, updated_at datetimeoffset(6), children_policy nvarchar(500), internet_description nvarchar(500), parking_description nvarchar(500), pet_policy nvarchar(500), smoking_policy nvarchar(500), cancellation_policy nvarchar(1000), payment_policy nvarchar(1000), primary key (id));
create table hotel_facilities (sort_order int not null, hotel_detail_id bigint not null, id bigint identity not null, facility_group nvarchar(255) check (facility_group in ('GENERAL','WELLNESS','BUSINESS','FOOD','OUTDOOR','FAMILY','ACCESSIBILITY')), facility_name nvarchar(255) not null, icon nvarchar(255), primary key (id));
create table hotel_languages (hotel_detail_id bigint not null, language nvarchar(255));
create table hotel_payment_methods (hotel_detail_id bigint not null, payment_method nvarchar(255));
create table hotel_rooms (active bit not null, available_quantity int check (available_quantity>=0), bed_count int check (bed_count>=1), breakfast_included bit not null, floor_number int, free_cancellation bit not null, instant_confirmation bit not null, max_adults int check (max_adults>=1), max_children int check (max_children>=0), max_guests int check (max_guests>=1), original_price numeric(15,2), price_from numeric(15,2), quantity int check (quantity>=0), room_size_sqm float(53), smoking_allowed bit not null, created_at datetimeoffset(6), hotel_detail_id bigint not null, id bigint identity not null, updated_at datetimeoffset(6), bed_type nvarchar(255) check (bed_type in ('SINGLE','DOUBLE','TWIN','QUEEN','KING','SOFA_BED','BUNK')), description nvarchar(max), room_code nvarchar(255) not null, room_name nvarchar(255) not null, room_type nvarchar(255) not null check (room_type in ('STANDARD','SUPERIOR','DELUXE','PREMIER','EXECUTIVE','SUITE','FAMILY','VILLA','BUNGALOW')), primary key (id));
create table hotel_services (available bit not null, hotel_detail_id bigint not null, id bigint identity not null, icon nvarchar(255), service_name nvarchar(255) not null, primary key (id));
create table inventory_reservations (check_in_date date not null, check_out_date date not null, number_of_rooms int not null, booking_id bigint not null, consumed_at datetimeoffset(6), created_at datetimeoffset(6), expired_at datetimeoffset(6), expires_at datetimeoffset(6) not null, id bigint identity not null, released_at datetimeoffset(6), room_id bigint not null, updated_at datetimeoffset(6), version bigint, status nvarchar(20) not null check (status in ('HELD','CONSUMED','RELEASED','EXPIRED')), primary key (id));
create table invoices (coupon_discount_amount numeric(15,2), credit_amount_used numeric(15,2), discount_amount numeric(15,2) not null, subtotal numeric(15,2) not null, tax_amount numeric(15,2) not null, total_amount numeric(15,2) not null, booking_id bigint not null, cancelled_at datetimeoffset(6), created_at datetimeoffset(6), hotel_id bigint not null, id bigint identity not null, issued_at datetimeoffset(6), paid_at datetimeoffset(6), payment_id bigint, updated_at datetimeoffset(6), user_id bigint not null, currency nvarchar(10) not null, status nvarchar(20) not null check (status in ('DRAFT','ISSUED','PAID','CANCELLED','REFUNDED')), coupon_code nvarchar(60), billing_address nvarchar(max), billing_email nvarchar(255), billing_name nvarchar(255), billing_phone nvarchar(255), invoice_number nvarchar(255), notes nvarchar(max), tax_code nvarchar(255), primary key (id));
create table loyalty_accounts (created_at datetimeoffset(6), current_balance bigint not null, id bigint identity not null, lifetime_points_earned bigint not null, updated_at datetimeoffset(6), user_id bigint not null, status nvarchar(20) not null check (status in ('ACTIVE','SUSPENDED','CLOSED')), primary key (id));
create table loyalty_points_redemptions (discount_amount numeric(15,2) not null, eligible_amount numeric(15,2) not null, value_per_unit_snapshot numeric(15,2) not null, applied_at datetimeoffset(6), booking_id bigint not null, cancelled_at datetimeoffset(6), created_at datetimeoffset(6), customer_id bigint not null, expires_at datetimeoffset(6), id bigint identity not null, loyalty_account_id bigint not null, points_per_unit_snapshot bigint not null, points_redeemed bigint not null, policy_id bigint not null, refunded_at datetimeoffset(6), released_at datetimeoffset(6), reserved_at datetimeoffset(6), updated_at datetimeoffset(6), version bigint, status nvarchar(20) not null check (status in ('RESERVED','APPLIED','RELEASED','REFUNDED','CANCELLED','EXPIRED')), redemption_reference nvarchar(40) not null, reason nvarchar(500), idempotency_key nvarchar(255), primary key (id));
create table loyalty_points_transactions (account_id bigint not null, balance_after bigint not null, balance_before bigint not null, created_at datetimeoffset(6), id bigint identity not null, points bigint not null, reference_id bigint, reference_type nvarchar(20) check (reference_type in ('BOOKING','REVIEW','ADMIN','SYSTEM','REDEMPTION')), transaction_type nvarchar(20) not null check (transaction_type in ('EARN_BOOKING','EARN_REVIEW','GRANT','ADJUSTMENT','REVERSAL','REDEMPTION_DEBIT','REDEMPTION_RELEASE','REDEMPTION_REFUND')), description nvarchar(255) not null, idempotency_key nvarchar(255), primary key (id));
create table loyalty_redemption_policies (active bit not null, maximum_discount_percentage int not null, minimum_final_payable_amount numeric(15,2) not null, value_per_unit numeric(15,2) not null, created_at datetimeoffset(6), effective_from datetimeoffset(6) not null, effective_until datetimeoffset(6), id bigint identity not null, minimum_redemption_points bigint not null, points_per_unit bigint not null, redemption_increment_points bigint not null, updated_at datetimeoffset(6), version bigint, policy_code nvarchar(60) not null, display_name nvarchar(255) not null, primary key (id));
create table media_assets (active bit not null, cover bit not null, sort_order int not null, created_at datetimeoffset(6), id bigint identity not null, owner_id bigint not null, updated_at datetimeoffset(6), uploaded_by bigint, media_type nvarchar(10) not null check (media_type in ('IMAGE','VIDEO','DOCUMENT')), owner_type nvarchar(20) not null check (owner_type in ('PLACE','ROOM','REVIEW','SUBMISSION','TRIP_DOCUMENT')), alt_text nvarchar(500), thumbnail_url nvarchar(1000), url nvarchar(1000) not null, primary key (id));
create table membership_benefit_definitions (active bit not null, numeric_value numeric(12,2), sort_order int not null, created_at datetimeoffset(6), id bigint identity not null, updated_at datetimeoffset(6), tier nvarchar(20) not null check (tier in ('BRONZE','SILVER','GOLD','PLATINUM','DIAMOND')), benefit_type nvarchar(30) not null check (benefit_type in ('POINTS_MULTIPLIER','MEMBER_ONLY_COUPONS','PRIORITY_SUPPORT','EARLY_ACCESS','LATE_CHECKOUT','EARLY_CHECKIN','ROOM_UPGRADE','FREE_BREAKFAST','AIRPORT_TRANSFER','CUSTOM')), description nvarchar(1000), text_value nvarchar(1000), name nvarchar(255) not null, primary key (id));
create table membership_tier_definitions (active bit not null, minimum_completed_bookings int not null, points_multiplier numeric(5,2) not null, redemption_discount_multiplier numeric(5,2) not null, sort_order int not null, created_at datetimeoffset(6), id bigint identity not null, minimum_lifetime_points bigint not null, updated_at datetimeoffset(6), tier nvarchar(20) not null check (tier in ('BRONZE','SILVER','GOLD','PLATINUM','DIAMOND')), description nvarchar(1000), display_name nvarchar(255) not null, primary key (id));
create table membership_tier_history (created_at datetimeoffset(6), effective_at datetimeoffset(6) not null, expires_at datetimeoffset(6), id bigint identity not null, membership_id bigint not null, reference_id bigint, new_tier nvarchar(20) not null check (new_tier in ('BRONZE','SILVER','GOLD','PLATINUM','DIAMOND')), previous_tier nvarchar(20) check (previous_tier in ('BRONZE','SILVER','GOLD','PLATINUM','DIAMOND')), reference_type nvarchar(20) check (reference_type in ('LOYALTY_ACCOUNT','BOOKING','ADMIN','SYSTEM')), change_type nvarchar(30) not null check (change_type in ('INITIAL_ENROLLMENT','AUTOMATIC_UPGRADE','AUTOMATIC_DOWNGRADE','MANUAL_UPGRADE','MANUAL_DOWNGRADE','EXPIRATION','REACTIVATION')), reason nvarchar(255) not null, primary key (id));
create table messages (read_by_partner bit not null, read_by_user bit not null, conversation_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, sender_user_id bigint not null, sender_role nvarchar(20) not null check (sender_role in ('USER','PARTNER','ADMIN','SYSTEM')), body nvarchar(max) not null, primary key (id));
create table notifications (is_read bit not null, created_at datetimeoffset(6), id bigint identity not null, read_at datetimeoffset(6), recipient_user_id bigint not null, related_entity_id bigint, notification_type nvarchar(20) not null check (notification_type in ('BOOKING','PAYMENT','RESERVATION','SYSTEM','PROMOTION','REVIEW','PARTNER','ADMIN','MESSAGE','TRIP')), priority nvarchar(20) not null check (priority in ('LOW','NORMAL','HIGH','URGENT')), related_entity_type nvarchar(20) check (related_entity_type in ('BOOKING','PAYMENT','HOTEL','ROOM','PROMOTION','SYSTEM','PARTNER','MESSAGE','TRIP')), title nvarchar(200) not null, message nvarchar(max) not null, primary key (id));
create table partner_activity_logs (actor_user_id bigint not null, created_at datetimeoffset(6), entity_id bigint, id bigint identity not null, partner_profile_id bigint not null, action nvarchar(255) not null, description nvarchar(max), entity_type nvarchar(255), primary key (id));
create table partner_payout_accounts (bank_account_last4 nvarchar(4) not null, created_at datetimeoffset(6), id bigint identity not null, partner_profile_id bigint not null, updated_at datetimeoffset(6), payout_method nvarchar(20) not null check (payout_method in ('BANK_TRANSFER','MANUAL')), status nvarchar(20) not null check (status in ('DRAFT','PENDING_VERIFICATION','VERIFIED','REJECTED','DISABLED')), account_holder_name nvarchar(255) not null, bank_name nvarchar(255) not null, primary key (id));
create table partner_profiles (approved_at datetimeoffset(6), approved_by bigint, created_at datetimeoffset(6), id bigint identity not null, rejected_at datetimeoffset(6), submitted_at datetimeoffset(6), updated_at datetimeoffset(6), user_id bigint not null, business_type nvarchar(20) not null check (business_type in ('HOTEL','RESTAURANT','CAFE','TOUR_OPERATOR','TRANSPORT','OTHER')), verification_status nvarchar(20) not null check (verification_status in ('DRAFT','SUBMITTED','APPROVED','REJECTED','SUSPENDED')), address nvarchar(255) not null, business_name nvarchar(255) not null, email nvarchar(255) not null, phone nvarchar(255) not null, reject_reason nvarchar(max), representative_name nvarchar(255) not null, tax_code nvarchar(255), website nvarchar(255), primary key (id));
create table partner_settings (booking_notification_enabled bit not null, notification_email_enabled bit not null, notification_in_app_enabled bit not null, notification_sms_enabled bit not null, payment_notification_enabled bit not null, promotion_notification_enabled bit not null, review_notification_enabled bit not null, created_at datetimeoffset(6), id bigint identity not null, partner_profile_id bigint not null, updated_at datetimeoffset(6), default_language nvarchar(255) not null, timezone nvarchar(255) not null, primary key (id));
create table partner_team_members (active bit not null, created_at datetimeoffset(6), id bigint identity not null, invited_at datetimeoffset(6), joined_at datetimeoffset(6), partner_profile_id bigint not null, updated_at datetimeoffset(6), user_id bigint not null, role nvarchar(20) not null check (role in ('OWNER','MANAGER','FRONT_DESK','FINANCE','VIEWER')), primary key (id));
create table payment_session_events (created_at datetimeoffset(6), id bigint identity not null, payment_session_id bigint not null, event_type nvarchar(20) not null check (event_type in ('CREATED','AUTHORIZED','CAPTURED','FAILED','CANCELLED','EXPIRED')), from_status nvarchar(20) check (from_status in ('NEW','PENDING','AUTHORIZED','CAPTURED','FAILED','CANCELLED','EXPIRED')), to_status nvarchar(20) not null check (to_status in ('NEW','PENDING','AUTHORIZED','CAPTURED','FAILED','CANCELLED','EXPIRED')), idempotency_key nvarchar(128), detail nvarchar(255), primary key (id));
create table payment_sessions (amount numeric(15,2) not null, booking_id bigint not null, created_at datetimeoffset(6), expires_at datetimeoffset(6), id bigint identity not null, payment_id bigint, updated_at datetimeoffset(6), version bigint, currency nvarchar(10) not null, provider nvarchar(20) not null check (provider in ('MOCK','VNPAY','PAYOS','MOMO','STRIPE','APPLE_PAY','GOOGLE_PAY','MANUAL')), status nvarchar(20) not null check (status in ('NEW','PENDING','AUTHORIZED','CAPTURED','FAILED','CANCELLED','EXPIRED')), callback_token nvarchar(64) not null, session_id nvarchar(64) not null, provider_reference nvarchar(128), checkout_url nvarchar(1000), primary key (id));
create table payments (amount numeric(15,2) not null, booking_id bigint not null, created_at datetimeoffset(6), failed_at datetimeoffset(6), id bigint identity not null, paid_at datetimeoffset(6), refunded_at datetimeoffset(6), updated_at datetimeoffset(6), currency nvarchar(10) not null, payment_method nvarchar(20) not null check (payment_method in ('MOCK','CASH','CARD','BANK_TRANSFER','VNPAY','MOMO','STRIPE','PAYOS')), provider nvarchar(20) not null check (provider in ('MOCK','VNPAY','PAYOS','MOMO','STRIPE','APPLE_PAY','GOOGLE_PAY','MANUAL')), status nvarchar(20) not null check (status in ('PENDING','PAID','FAILED','CANCELLED','REFUNDED')), checkout_url nvarchar(1000), failure_reason nvarchar(max), payment_code nvarchar(255), provider_transaction_id nvarchar(255), primary key (id));
create table personalization_rules (active bit not null, priority int not null, created_at datetimeoffset(6), id bigint identity not null, target_coupon_definition_id bigint, target_hotel_id bigint, target_place_id bigint, target_promotion_id bigint, updated_at datetimeoffset(6), valid_from datetimeoffset(6), valid_until datetimeoffset(6), version bigint, minimum_membership_tier nvarchar(20) check (minimum_membership_tier in ('BRONZE','SILVER','GOLD','PLATINUM','DIAMOND')), rule_type nvarchar(30) not null check (rule_type in ('WISHLIST_AFFINITY','RECENTLY_VIEWED','BOOKING_HISTORY','DESTINATION_AFFINITY','TRAVEL_STYLE','MEMBERSHIP_TIER','LOYALTY_ACTIVITY','ABANDONED_INTEREST','REENGAGEMENT','TRENDING','MANUAL')), rule_code nvarchar(80) not null, target_place_type nvarchar(100), configuration_json nvarchar(max), description nvarchar(max), name nvarchar(255) not null, primary key (id));
create table place_amenities (amenity_id bigint not null, id bigint identity not null, place_id bigint not null, primary key (id));
create table place_images (cover bit not null, sort_order int not null, created_at datetimeoffset(6), id bigint identity not null, place_id bigint not null, caption nvarchar(500), image_url nvarchar(255) not null, primary key (id));
create table place_metadata (estimated_visit_minutes int, family_friendly bit not null, indoor bit not null, kid_friendly bit not null, outdoor bit not null, pet_friendly bit not null, photography_spot bit not null, rainy_day_suitable bit not null, romantic bit not null, sunrise_spot bit not null, sunset_spot bit not null, wheelchair_friendly bit not null, created_at datetimeoffset(6), id bigint identity not null, place_id bigint not null, updated_at datetimeoffset(6), accessibility_level nvarchar(20) check (accessibility_level in ('LOW','MEDIUM','HIGH')), crowd_level nvarchar(20) check (crowd_level in ('LOW','MEDIUM','HIGH')), difficulty_level nvarchar(20) check (difficulty_level in ('EASY','MODERATE','HARD')), estimated_budget_level nvarchar(20) check (estimated_budget_level in ('FREE','LOW','MEDIUM','HIGH','LUXURY')), notes nvarchar(2000), primary key (id));
create table place_metadata_seasons (metadata_id bigint not null, season nvarchar(20) check (season in ('SPRING','SUMMER','AUTUMN','WINTER','ALL_YEAR')));
create table place_metadata_travel_styles (metadata_id bigint not null, style nvarchar(20) check (style in ('SOLO','COUPLE','FAMILY','FRIENDS','BUSINESS','BACKPACKER','LUXURY')));
create table place_metadata_visit_times (metadata_id bigint not null, visit_time nvarchar(20) check (visit_time in ('EARLY_MORNING','MORNING','AFTERNOON','SUNSET','EVENING','NIGHT')));
create table place_metadata_weather_types (metadata_id bigint not null, weather_type nvarchar(20) check (weather_type in ('SUNNY','CLOUDY','RAINY','COOL','ANY')));
create table place_opening_hours (close_time time, closed bit not null, day_of_week int not null check ((day_of_week>=1) and (day_of_week<=7)), open_time time, id bigint identity not null, place_id bigint not null, primary key (id));
create table place_tags (id bigint identity not null, place_id bigint not null, tag nvarchar(100) not null, tag_normalized nvarchar(100) not null, primary key (id));
create table places (active bit not null, featured bit not null, latitude float(53), longitude float(53), price_level int not null check ((price_level<=4) and (price_level>=0)), rating_avg float(53) not null, review_count int not null check (review_count>=0), verified bit not null, administrative_unit_id bigint not null, approved_at datetimeoffset(6), approved_by_id bigint, category_id bigint not null, created_at datetimeoffset(6), created_by_id bigint not null, id bigint identity not null, owner_partner_profile_id bigint, owner_user_id bigint, subcategory_id bigint, updated_at datetimeoffset(6), status nvarchar(20) not null check (status in ('DRAFT','PENDING_REVIEW','APPROVED','PUBLISHED','HIDDEN','ARCHIVED','REJECTED')), google_map_url nvarchar(500), short_description nvarchar(500), address nvarchar(255) not null, description nvarchar(max), email nvarchar(255), facebook nvarchar(255), instagram nvarchar(255), name nvarchar(255) not null, name_normalized nvarchar(255) not null, phone nvarchar(255), slug nvarchar(255) not null, website nvarchar(255), primary key (id));
create table promotions (active bit not null, discount_value numeric(15,2) not null, end_date date not null, max_discount_amount numeric(15,2), minimum_spend numeric(15,2), minimum_stay int check (minimum_stay>=1), priority int not null, stackable bit not null, start_date date not null, created_at datetimeoffset(6), id bigint identity not null, target_id bigint, updated_at datetimeoffset(6), code nvarchar(255), description nvarchar(max), discount_type nvarchar(255) not null check (discount_type in ('PERCENTAGE','FIXED_AMOUNT')), name nvarchar(255) not null, promotion_type nvarchar(255) not null check (promotion_type in ('GENERAL','ROOM','HOTEL','MEMBER','EARLY_BIRD','LAST_MINUTE','WEEKEND','HOLIDAY')), target_type nvarchar(255) not null check (target_type in ('ALL','HOTEL','ROOM')), primary key (id));
create table rate_plan_occupancy_prices (adults int not null, child_supplement numeric(15,2), children int not null, extra_bed_supplement numeric(15,2), price_per_night numeric(15,2) not null, created_at datetimeoffset(6), id bigint identity not null, rate_plan_id bigint not null, updated_at datetimeoffset(6), version bigint, primary key (id));
create table rate_plans (active bit not null, adjustment_value numeric(15,2), cancellation_deadline_hours int, cancellation_penalty_percent numeric(5,2), child_pricing_enabled bit not null, closed_to_arrival bit not null, closed_to_departure bit not null, end_date date not null, extra_bed_price numeric(15,2), max_advance_booking_days int, max_stay_nights int, min_advance_booking_days int, min_stay_nights int, occupancy_pricing_enabled bit not null, price_per_night numeric(15,2) not null, priority int not null, refundable bit not null, start_date date not null, created_at datetimeoffset(6), id bigint identity not null, parent_rate_plan_id bigint, room_id bigint not null, updated_at datetimeoffset(6), version bigint, adjustment_type nvarchar(10) check (adjustment_type in ('FIXED_AMOUNT','PERCENTAGE')), source_type nvarchar(10) not null check (source_type in ('BASE','DERIVED')), meal_plan_type nvarchar(20) check (meal_plan_type in ('ROOM_ONLY','BREAKFAST','HALF_BOARD','FULL_BOARD','ALL_INCLUSIVE')), cancellation_policy_type nvarchar(30) check (cancellation_policy_type in ('FREE_CANCELLATION','PARTIALLY_REFUNDABLE','NON_REFUNDABLE','CUSTOM')), code nvarchar(60), description nvarchar(max), rate_name nvarchar(255) not null, rate_type nvarchar(255) not null check (rate_type in ('STANDARD','PROMOTIONAL','MEMBER','EARLY_BIRD','LAST_MINUTE')), primary key (id));
create table recently_viewed_places (id bigint identity not null, place_id bigint not null, user_id bigint not null, viewed_at datetimeoffset(6) not null, primary key (id));
create table referral_campaigns (active bit not null, invitee_reward_credit_amount numeric(15,2), invitee_reward_credit_currency nvarchar(3), inviter_reward_credit_amount numeric(15,2), inviter_reward_credit_currency nvarchar(3), minimum_qualifying_booking_amount numeric(15,2), created_at datetimeoffset(6), effective_from datetimeoffset(6) not null, effective_until datetimeoffset(6), id bigint identity not null, invitee_reward_coupon_definition_id bigint, invitee_reward_points bigint, inviter_reward_coupon_definition_id bigint, inviter_reward_points bigint, updated_at datetimeoffset(6), version bigint, code nvarchar(60) not null, name nvarchar(255) not null, primary key (id));
create table referral_codes (created_at datetimeoffset(6), id bigint identity not null, owner_id bigint not null, code nvarchar(32) not null, primary key (id));
create table referral_rewards (campaign_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, invitee_id bigint not null, inviter_id bigint not null, qualified_at datetimeoffset(6), qualifying_booking_id bigint, referral_code_id bigint not null, rewarded_at datetimeoffset(6), updated_at datetimeoffset(6), used_at datetimeoffset(6) not null, version bigint, status nvarchar(20) not null check (status in ('USED','REWARDED')), primary key (id));
create table reviews (helpful_count int not null, rating_cleanliness int, rating_facilities int, rating_location int, rating_overall int not null, rating_service int, rating_value int, reported_count int not null, approved_at datetimeoffset(6), booking_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, partner_replied_at datetimeoffset(6), partner_replied_by_profile_id bigint, partner_reply_updated_at datetimeoffset(6), place_id bigint not null, rejected_at datetimeoffset(6), updated_at datetimeoffset(6), user_id bigint not null, status nvarchar(20) not null check (status in ('PENDING','APPROVED','REJECTED','HIDDEN','REPORTED')), content nvarchar(max), partner_reply nvarchar(max), reject_reason nvarchar(max), title nvarchar(255), primary key (id));
create table room_amenities (amenity_id bigint not null, id bigint identity not null, room_id bigint not null, primary key (id));
create table room_inventory (available_inventory int not null check (available_inventory>=0), blocked_inventory int not null check (blocked_inventory>=0), closed_arrival bit not null, closed_departure bit not null, inventory_date date not null, maintenance_inventory int not null check (maintenance_inventory>=0), sold_inventory int not null check (sold_inventory>=0), stop_sell bit not null, total_inventory int not null check (total_inventory>=0), created_at datetimeoffset(6), id bigint identity not null, room_id bigint not null, updated_at datetimeoffset(6), primary key (id));
create table saved_collection_places (position int not null, collection_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, place_id bigint not null, primary key (id));
create table saved_collections (private_collection bit not null, sort_order int not null, created_at datetimeoffset(6), id bigint identity not null, owner_id bigint not null, updated_at datetimeoffset(6), description nvarchar(1000), cover_image_url nvarchar(2048), name nvarchar(255) not null, primary key (id));
create table timeline_item (day_number int not null check (day_number>=1), end_time time not null, start_time time not null, id bigint identity not null, place_id bigint, trip_id bigint not null, notes nvarchar(1200), title nvarchar(255) not null, primary key (id));
create table travel_credit_accounts (balance numeric(15,2) not null, created_at datetimeoffset(6), id bigint identity not null, updated_at datetimeoffset(6), user_id bigint not null, currency nvarchar(10) not null, primary key (id));
create table travel_credit_transactions (amount numeric(15,2) not null, balance_after numeric(15,2) not null, balance_before numeric(15,2) not null, expires_at date, account_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, reference_id bigint, reference_type nvarchar(20) check (reference_type in ('BOOKING','PAYMENT','REFUND','PROMOTION','ADMIN','SYSTEM')), transaction_type nvarchar(20) not null check (transaction_type in ('GRANT','PROMOTION','REFUND_CREDIT','ADJUSTMENT','REDEMPTION','EXPIRATION','REVERSAL')), description nvarchar(255) not null, idempotency_key nvarchar(255), primary key (id));
create table travel_wallet_items (archived bit not null, expiry_reminder_enabled bit not null, favorite bit not null, valid_from date, valid_until date, booking_id bigint, created_at datetimeoffset(6), id bigint identity not null, invoice_id bigint, trip_plan_document_id bigint, trip_plan_id bigint, updated_at datetimeoffset(6), user_id bigint not null, status nvarchar(20) not null check (status in ('ACTIVE','UPCOMING','EXPIRED','CANCELLED','ARCHIVED')), wallet_item_type nvarchar(30) not null check (wallet_item_type in ('PASSPORT','VISA','BOARDING_PASS','FLIGHT_TICKET','TRAIN_TICKET','BUS_TICKET','HOTEL_VOUCHER','TOUR_VOUCHER','INSURANCE','BOOKING_CONFIRMATION','INVOICE','RECEIPT','ITINERARY','OTHER')), display_title nvarchar(255) not null, issuer nvarchar(255), reference_number_masked nvarchar(255), primary key (id));
create table trip (budget float(53) not null, end_date date not null, start_date date not null, travelers int not null check (travelers>=1), id bigint identity not null, owner_id bigint not null, destination nvarchar(255) not null, image_url nvarchar(255), title nvarchar(255) not null, primary key (id));
create table trip_plan_budgets (total_budget numeric(38,2) not null, created_at datetimeoffset(6), id bigint identity not null, trip_plan_id bigint not null, updated_at datetimeoffset(6), currency nvarchar(255) not null, notes nvarchar(max), primary key (id));
create table trip_plan_collaborators (active bit not null, accepted_at datetimeoffset(6), created_at datetimeoffset(6), id bigint identity not null, invited_at datetimeoffset(6), trip_plan_id bigint not null, updated_at datetimeoffset(6), user_id bigint not null, role nvarchar(255) not null check (role in ('VIEWER','EDITOR')), primary key (id));
create table trip_plan_days (date date, day_number int not null, id bigint identity not null, trip_plan_id bigint not null, notes nvarchar(max), title nvarchar(255), primary key (id));
create table trip_plan_documents (pinned bit not null, created_at datetimeoffset(6), id bigint identity not null, media_asset_id bigint not null, trip_plan_day_id bigint, trip_plan_id bigint not null, trip_plan_item_id bigint, updated_at datetimeoffset(6), uploaded_by_user_id bigint not null, document_type nvarchar(255) not null check (document_type in ('FLIGHT_TICKET','HOTEL_BOOKING','TRAIN_TICKET','BUS_TICKET','PASSPORT','VISA','INSURANCE','TOUR','RECEIPT','PDF','IMAGE','OTHER')), notes nvarchar(max), title nvarchar(255), primary key (id));
create table trip_plan_expenses (amount numeric(38,2) not null, expense_date date not null, created_at datetimeoffset(6), id bigint identity not null, paid_by_user_id bigint not null, trip_plan_day_id bigint, trip_plan_id bigint not null, trip_plan_item_id bigint, updated_at datetimeoffset(6), category nvarchar(255) not null check (category in ('ACCOMMODATION','FOOD','TRANSPORT','ATTRACTION','SHOPPING','HEALTH','VISA','INSURANCE','OTHER')), currency nvarchar(255) not null, notes nvarchar(max), title nvarchar(255) not null, primary key (id));
create table trip_plan_items (end_time time, estimated_cost numeric(38,2), latitude float(53), longitude float(53), sort_order int not null, start_time time, created_at datetimeoffset(6), id bigint identity not null, place_id bigint, trip_plan_day_id bigint not null, custom_description nvarchar(max), custom_title nvarchar(255), transportation_note nvarchar(255), primary key (id));
create table trip_plan_notes (pinned bit not null, author_user_id bigint not null, created_at datetimeoffset(6), id bigint identity not null, trip_plan_day_id bigint, trip_plan_id bigint not null, trip_plan_item_id bigint, updated_at datetimeoffset(6), content nvarchar(max) not null, mood nvarchar(255) check (mood in ('HAPPY','EXCITED','CALM','TIRED','STRESSED','NEUTRAL')), note_type nvarchar(255) not null check (note_type in ('NOTE','JOURNAL','REMINDER','IDEA','MEMORY')), photo_url nvarchar(255), title nvarchar(255), primary key (id));
create table trip_plan_packing_items (checked bit not null, quantity int not null, sort_order int not null, assigned_to_user_id bigint, checked_at datetimeoffset(6), created_at datetimeoffset(6), id bigint identity not null, trip_plan_id bigint not null, updated_at datetimeoffset(6), category nvarchar(255) not null check (category in ('DOCUMENTS','CLOTHES','TOILETRIES','ELECTRONICS','MEDICINE','MONEY','FOOD','BABY','PET','OTHER')), label nvarchar(255) not null, notes nvarchar(max), primary key (id));
create table trip_plan_reminders (delivery_attempts int not null, completed_at datetimeoffset(6), created_at datetimeoffset(6), delivered_at datetimeoffset(6), document_id bigint, id bigint identity not null, reminder_at datetimeoffset(6) not null, source_id bigint, trip_plan_day_id bigint, trip_plan_id bigint, trip_plan_item_id bigint, updated_at datetimeoffset(6), user_id bigint not null, last_delivery_error nvarchar(max), message nvarchar(max), reminder_type nvarchar(255) not null check (reminder_type in ('CUSTOM','DOCUMENT','CHECK_IN','FLIGHT','ACTIVITY','PAYMENT','PACKING','OTHER')), source_key nvarchar(255), source_type nvarchar(255), status nvarchar(255) not null check (status in ('PENDING','COMPLETED','CANCELLED')), title nvarchar(255) not null, primary key (id));
create table trip_plans (end_date date not null, is_public bit not null, start_date date not null, created_at datetimeoffset(6), id bigint identity not null, updated_at datetimeoffset(6), user_id bigint not null, cover_image nvarchar(255), description nvarchar(max), destination nvarchar(255), status nvarchar(255) not null check (status in ('PLANNING','ACTIVE','COMPLETED','CANCELLED')), title nvarchar(255) not null, primary key (id));
create table user_interest_categories (profile_id bigint not null, category nvarchar(200));
create table user_interest_profiles (signal_count int not null, created_at datetimeoffset(6), id bigint identity not null, last_recalculated_at datetimeoffset(6), updated_at datetimeoffset(6), user_id bigint not null, preferred_accessibility_level nvarchar(20) check (preferred_accessibility_level in ('LOW','MEDIUM','HIGH')), preferred_budget_level nvarchar(20) check (preferred_budget_level in ('FREE','LOW','MEDIUM','HIGH','LUXURY')), preferred_crowd_level nvarchar(20) check (preferred_crowd_level in ('LOW','MEDIUM','HIGH')), primary key (id));
create table user_interest_provinces (profile_id bigint not null, province nvarchar(200));
create table user_interest_tags (profile_id bigint not null, tag nvarchar(200));
create table user_interest_travel_styles (profile_id bigint not null, style nvarchar(20) check (style in ('SOLO','COUPLE','FAMILY','FRIENDS','BUSINESS','BACKPACKER','LUXURY')));
create table user_interest_weather_types (profile_id bigint not null, weather_type nvarchar(20) check (weather_type in ('SUNNY','CLOUDY','RAINY','COOL','ANY')));
create table users (enabled bit not null, created_at datetimeoffset(6), id bigint identity not null, updated_at datetimeoffset(6), email nvarchar(255) not null, full_name nvarchar(255) not null, password_hash nvarchar(255) not null, role nvarchar(255), primary key (id));
create table wishlist_items (created_at datetimeoffset(6), id bigint identity not null, place_id bigint not null, wishlist_id bigint not null, note nvarchar(500), primary key (id));
create table wishlists (created_at datetimeoffset(6), id bigint identity not null, updated_at datetimeoffset(6), user_id bigint not null, primary key (id));
create index idx_au_parent on administrative_units (parent_id);
create unique nonclustered index UKkm1hnn07q97r7u0scj86b7hrw on administrative_units (code) where code is not null;
alter table administrative_units add constraint UKj76iqtxxer05n55rr2xaghilj unique (slug);
alter table amenities add constraint UK26crry6wn4jr1tu04otkna7h5 unique (slug);
create index idx_booking_check_in_audits_booking_id on booking_check_in_audits (booking_id);
create index idx_booking_check_out_audits_booking_id on booking_check_out_audits (booking_id);
create index idx_booking_modifications_booking_id on booking_modifications (booking_id);
create index idx_bookings_user_id on bookings (user_id);
create index idx_bookings_hotel_id on bookings (hotel_id);
create index idx_bookings_room_id on bookings (room_id);
create index idx_bookings_status on bookings (status);
create index idx_bookings_check_in on bookings (check_in_date);
create unique nonclustered index idx_bookings_code on bookings (booking_code) where booking_code is not null;
create index idx_cat_parent on categories (parent_id);
alter table categories add constraint UKoul14ho7bctbefv8jywp5v3i2 unique (slug);
create index idx_conversations_booking_id on conversations (booking_id);
create index idx_conversations_user_id on conversations (user_id);
create index idx_conversations_partner_profile_id on conversations (partner_profile_id);
create index idx_conversations_status on conversations (status);
alter table coupon_definitions add constraint uk_coupon_definition_code unique (code);
create index idx_customer_coupons_user_id on customer_coupons (user_id);
create index idx_customer_coupons_definition_id on customer_coupons (coupon_definition_id);
alter table customer_memberships add constraint uk_customer_membership_user unique (user_id);
create unique nonclustered index UKs5l42uynrlb8i6mvq74qwnbju on customer_memberships (loyalty_account_id) where loyalty_account_id is not null;
alter table customer_profiles add constraint idx_customer_profiles_user_id unique (user_id);
create index idx_customer_rec_user on customer_recommendations (user_id);
create index idx_customer_rec_user_type on customer_recommendations (user_id, recommendation_type);
create index idx_customer_rec_target_key on customer_recommendations (target_key);
alter table gift_card_products add constraint uk_gift_card_product_code unique (product_code);
create index idx_gift_card_tx_gift_card_id on gift_card_transactions (gift_card_id);
create unique nonclustered index uk_gift_card_tx_idempotency_key on gift_card_transactions (idempotency_key) where idempotency_key is not null;
create index idx_gift_card_status on gift_cards (status);
create index idx_gift_card_purchaser_user_id on gift_cards (purchaser_user_id);
create index idx_gift_card_recipient_user_id on gift_cards (recipient_user_id);
create index idx_gift_card_expires_at on gift_cards (expires_at);
create index idx_gift_card_issued_at on gift_cards (issued_at);
create index idx_gift_card_product_id on gift_cards (product_id);
alter table gift_cards add constraint uk_gift_card_code unique (gift_card_code);
alter table hotel_details add constraint UKrdpbu9e15kjpn75ttsh0t8o4v unique (place_id);
alter table hotel_rooms add constraint uk_hotel_room_code unique (hotel_detail_id, room_code);
create index idx_inventory_reservation_status on inventory_reservations (status);
create index idx_inventory_reservation_expires_at on inventory_reservations (expires_at);
alter table inventory_reservations add constraint uk_inventory_reservation_booking unique (booking_id);
create index idx_invoices_user_id on invoices (user_id);
create index idx_invoices_status on invoices (status);
alter table invoices add constraint idx_invoices_booking_id unique (booking_id);
create unique nonclustered index idx_invoices_number on invoices (invoice_number) where invoice_number is not null;
alter table loyalty_accounts add constraint uk_loyalty_account_user unique (user_id);
create index idx_loyalty_redemption_booking on loyalty_points_redemptions (booking_id);
create index idx_loyalty_redemption_customer on loyalty_points_redemptions (customer_id);
create index idx_loyalty_redemption_account on loyalty_points_redemptions (loyalty_account_id);
create index idx_loyalty_redemption_status on loyalty_points_redemptions (status);
create index idx_loyalty_redemption_expires_at on loyalty_points_redemptions (expires_at);
alter table loyalty_points_redemptions add constraint uk_loyalty_redemption_reference unique (redemption_reference);
create unique nonclustered index uk_loyalty_redemption_idempotency_key on loyalty_points_redemptions (idempotency_key) where idempotency_key is not null;
create index idx_loyalty_tx_account_id on loyalty_points_transactions (account_id);
create unique nonclustered index uk_loyalty_tx_idempotency_key on loyalty_points_transactions (idempotency_key) where idempotency_key is not null;
create index idx_loyalty_redemption_policy_active on loyalty_redemption_policies (active);
create index idx_loyalty_redemption_policy_effective_from on loyalty_redemption_policies (effective_from);
alter table loyalty_redemption_policies add constraint uk_loyalty_redemption_policy_code unique (policy_code);
create index idx_media_owner on media_assets (owner_type, owner_id);
create index idx_media_active on media_assets (owner_type, owner_id, active);
create index idx_membership_benefit_tier on membership_benefit_definitions (tier);
alter table membership_tier_definitions add constraint uk_membership_tier_definition_tier unique (tier);
create index idx_membership_tier_history_membership_id on membership_tier_history (membership_id);
create index idx_messages_conversation_id on messages (conversation_id);
create index idx_notifications_recipient on notifications (recipient_user_id);
create index idx_notifications_recipient_read on notifications (recipient_user_id, is_read);
create index idx_notifications_created_at on notifications (created_at);
create index idx_partner_activity_logs_profile_id on partner_activity_logs (partner_profile_id);
create index idx_partner_activity_logs_created_at on partner_activity_logs (created_at);
alter table partner_payout_accounts add constraint idx_partner_payout_accounts_profile_id unique (partner_profile_id);
create index idx_partner_profiles_status on partner_profiles (verification_status);
alter table partner_profiles add constraint idx_partner_profiles_user_id unique (user_id);
alter table partner_settings add constraint idx_partner_settings_profile_id unique (partner_profile_id);
create index idx_partner_team_members_profile_id on partner_team_members (partner_profile_id);
create index idx_partner_team_members_user_id on partner_team_members (user_id);
alter table partner_team_members add constraint uk_partner_team_member_profile_user unique (partner_profile_id, user_id);
create index idx_payment_session_event_session_id on payment_session_events (payment_session_id);
create unique nonclustered index uk_payment_session_event_idempotency_key on payment_session_events (idempotency_key) where idempotency_key is not null;
create index idx_payment_session_status on payment_sessions (status);
create index idx_payment_session_booking_id on payment_sessions (booking_id);
create index idx_payment_session_expires_at on payment_sessions (expires_at);
alter table payment_sessions add constraint uk_payment_session_session_id unique (session_id);
create index idx_payments_booking_id on payments (booking_id);
create index idx_payments_status on payments (status);
create unique nonclustered index idx_payments_code on payments (payment_code) where payment_code is not null;
create index idx_personalization_rule_active on personalization_rules (active);
create index idx_personalization_rule_type on personalization_rules (rule_type);
alter table personalization_rules add constraint uk_personalization_rule_code unique (rule_code);
alter table place_amenities add constraint uk_place_amenity unique (place_id, amenity_id);
create index idx_place_images_place_id on place_images (place_id);
alter table place_metadata add constraint UKt0qpql30gjabmtigdtn89jpgi unique (place_id);
create index idx_poh_place_id on place_opening_hours (place_id);
create index idx_place_tags_place_id on place_tags (place_id);
create index idx_places_status on places (status);
create index idx_places_category_id on places (category_id);
create index idx_places_subcategory_id on places (subcategory_id);
create index idx_places_admin_unit_id on places (administrative_unit_id);
create index idx_places_name_normalized on places (name_normalized);
create index idx_places_price_level on places (price_level);
create index idx_places_rating_avg on places (rating_avg);
create index idx_places_featured on places (featured);
create index idx_places_verified on places (verified);
alter table places add constraint idx_places_slug unique (slug);
create unique nonclustered index uk_promotion_code on promotions (code) where code is not null;
alter table rate_plan_occupancy_prices add constraint uk_occupancy_price_plan_occupancy unique (rate_plan_id, adults, children);
create unique nonclustered index uk_rate_plan_room_code on rate_plans (room_id, code) where room_id is not null and code is not null;
create index idx_recently_viewed_user_id on recently_viewed_places (user_id);
create index idx_recently_viewed_viewed_at on recently_viewed_places (viewed_at);
alter table recently_viewed_places add constraint uk_recently_viewed_user_place unique (user_id, place_id);
create index idx_referral_campaign_active on referral_campaigns (active);
create index idx_referral_campaign_effective_from on referral_campaigns (effective_from);
alter table referral_campaigns add constraint uk_referral_campaign_code unique (code);
alter table referral_codes add constraint uk_referral_code_owner unique (owner_id);
alter table referral_codes add constraint uk_referral_code_code unique (code);
create index idx_referral_reward_inviter on referral_rewards (inviter_id);
create index idx_referral_reward_status on referral_rewards (status);
alter table referral_rewards add constraint uk_referral_reward_invitee unique (invitee_id);
create index idx_reviews_user_id on reviews (user_id);
create index idx_reviews_place_id on reviews (place_id);
create index idx_reviews_status on reviews (status);
alter table reviews add constraint idx_reviews_booking_id unique (booking_id);
alter table room_amenities add constraint uk_room_amenity unique (room_id, amenity_id);
alter table room_inventory add constraint uk_room_inventory_date unique (room_id, inventory_date);
create index idx_saved_collection_places_collection_id on saved_collection_places (collection_id);
create index idx_saved_collection_places_place_id on saved_collection_places (place_id);
alter table saved_collection_places add constraint uk_saved_collection_place unique (collection_id, place_id);
create index idx_saved_collections_owner_id on saved_collections (owner_id);
alter table travel_credit_accounts add constraint uk_travel_credit_account_user unique (user_id);
create index idx_travel_credit_tx_account_id on travel_credit_transactions (account_id);
create unique nonclustered index uk_travel_credit_tx_idempotency_key on travel_credit_transactions (idempotency_key) where idempotency_key is not null;
create index idx_travel_wallet_items_user_id on travel_wallet_items (user_id);
create index idx_travel_wallet_items_trip_plan_id on travel_wallet_items (trip_plan_id);
create index idx_travel_wallet_items_document_id on travel_wallet_items (trip_plan_document_id);
create index idx_travel_wallet_items_booking_id on travel_wallet_items (booking_id);
create index idx_travel_wallet_items_invoice_id on travel_wallet_items (invoice_id);
alter table trip_plan_budgets add constraint idx_trip_plan_budgets_trip_plan_id unique (trip_plan_id);
create index idx_trip_plan_collaborators_trip_plan_id on trip_plan_collaborators (trip_plan_id);
create index idx_trip_plan_collaborators_user_id on trip_plan_collaborators (user_id);
alter table trip_plan_collaborators add constraint uk_trip_plan_collaborator_trip_user unique (trip_plan_id, user_id);
create index idx_trip_plan_days_trip_plan_id on trip_plan_days (trip_plan_id);
alter table trip_plan_days add constraint uk_trip_plan_day_number unique (trip_plan_id, day_number);
create index idx_trip_plan_documents_trip_plan_id on trip_plan_documents (trip_plan_id);
create index idx_trip_plan_documents_trip_plan_day_id on trip_plan_documents (trip_plan_day_id);
create index idx_trip_plan_documents_trip_plan_item_id on trip_plan_documents (trip_plan_item_id);
create index idx_trip_plan_documents_media_asset_id on trip_plan_documents (media_asset_id);
create index idx_trip_plan_expenses_trip_plan_id on trip_plan_expenses (trip_plan_id);
create index idx_trip_plan_expenses_trip_plan_day_id on trip_plan_expenses (trip_plan_day_id);
create index idx_trip_plan_expenses_trip_plan_item_id on trip_plan_expenses (trip_plan_item_id);
create index idx_trip_plan_items_trip_plan_day_id on trip_plan_items (trip_plan_day_id);
create index idx_trip_plan_notes_trip_plan_id on trip_plan_notes (trip_plan_id);
create index idx_trip_plan_notes_trip_plan_day_id on trip_plan_notes (trip_plan_day_id);
create index idx_trip_plan_notes_trip_plan_item_id on trip_plan_notes (trip_plan_item_id);
create index idx_trip_plan_packing_items_trip_plan_id on trip_plan_packing_items (trip_plan_id);
create index idx_trip_plan_reminders_trip_plan_id on trip_plan_reminders (trip_plan_id);
create index idx_trip_plan_reminders_trip_plan_day_id on trip_plan_reminders (trip_plan_day_id);
create index idx_trip_plan_reminders_trip_plan_item_id on trip_plan_reminders (trip_plan_item_id);
create index idx_trip_plan_reminders_document_id on trip_plan_reminders (document_id);
create index idx_trip_plan_reminders_reminder_at on trip_plan_reminders (reminder_at);
create unique nonclustered index UKgx6g3ej6ev95hosjf7ort56pg on trip_plan_reminders (source_key) where source_key is not null;
create index idx_trip_plans_user_id on trip_plans (user_id);
alter table user_interest_profiles add constraint uk_user_interest_profile_user unique (user_id);
alter table users add constraint idx_users_email unique (email);
create index idx_wishlist_items_wishlist_id on wishlist_items (wishlist_id);
create index idx_wishlist_items_place_id on wishlist_items (place_id);
alter table wishlist_items add constraint uk_wishlist_item_place unique (wishlist_id, place_id);
alter table wishlists add constraint idx_wishlists_user_id unique (user_id);
alter table administrative_units add constraint FK5yd20yncxddovvnc9no2hp2cf foreign key (parent_id) references administrative_units;
alter table booking_check_in_audits add constraint FKtqv0kwkm7479nl24yf9njvgbb foreign key (booking_id) references bookings;
alter table booking_check_out_audits add constraint FK9yl0rje0yt8xrpfapo7gpm8h9 foreign key (booking_id) references bookings;
alter table booking_modifications add constraint FKcj2dtpn5qj62soko1r28gqhb0 foreign key (booking_id) references bookings;
alter table bookings add constraint FKdihdub3g3mdf7vxvlj9qjkega foreign key (hotel_id) references places;
alter table bookings add constraint FK9xm0qcqmha72qxvqvgriv0fsg foreign key (room_id) references hotel_rooms;
alter table bookings add constraint FKeyog2oic85xg7hsu2je2lx3s6 foreign key (user_id) references users;
alter table categories add constraint FKsaok720gsu4u2wrgbk10b5n8d foreign key (parent_id) references categories;
alter table conversations add constraint FK8q82g8gjmdej1448ui67bbnfq foreign key (booking_id) references bookings;
alter table conversations add constraint FKthfunta0jonlvbis1x8v4dws0 foreign key (partner_profile_id) references partner_profiles;
alter table conversations add constraint FKpltqvfcbkql9svdqwh0hw4g1d foreign key (user_id) references users;
alter table customer_coupons add constraint FKqnk8a8wakldb8dhycn7r49nw6 foreign key (booking_id) references bookings;
alter table customer_coupons add constraint FKjel6dlqka2ntm0vxl3khi1fs7 foreign key (coupon_definition_id) references coupon_definitions;
alter table customer_coupons add constraint FKoqbresnnnxgo21p0l664lmwow foreign key (user_id) references users;
alter table customer_memberships add constraint FK9w5lixakdiamk82hahnvd5yiv foreign key (loyalty_account_id) references loyalty_accounts;
alter table customer_memberships add constraint FKik494sivw3db4ybrweiy25t6a foreign key (user_id) references users;
alter table customer_profiles add constraint FK69orkdj1un5rh845ngvvmd1xs foreign key (user_id) references users;
alter table customer_recommendations add constraint FKtlkif7i829dfrlb41sv8i5qvs foreign key (coupon_definition_id) references coupon_definitions;
alter table customer_recommendations add constraint FKls34uatll44qo54dmy0m5fs7q foreign key (hotel_id) references places;
alter table customer_recommendations add constraint FKbyd3w4af792yuh21nvsop09ej foreign key (place_id) references places;
alter table customer_recommendations add constraint FKkwayibfmbir3mxjcy3l3tjr6u foreign key (promotion_id) references promotions;
alter table customer_recommendations add constraint FKcnw5ad717i2xly7gmuvua466x foreign key (room_id) references hotel_rooms;
alter table customer_recommendations add constraint FKtr9e2ah5u46an7oxkh2hkdu0d foreign key (source_rule_id) references personalization_rules;
alter table customer_recommendations add constraint FKruo3xgr8u8prq8s7yenfx1dna foreign key (user_id) references users;
alter table expense add constraint FKhvt1sy7allwvp8x38s636adka foreign key (trip_id) references trip;
alter table gift_card_transactions add constraint FK9o1y119mydj114oqaym15a92y foreign key (gift_card_id) references gift_cards;
alter table gift_cards add constraint FKj8wfpdh98a4ep835cmgq5wrdy foreign key (product_id) references gift_card_products;
alter table gift_cards add constraint FKiv8uofufysf509mnmvchvhm04 foreign key (purchaser_user_id) references users;
alter table gift_cards add constraint FKescr02h1ltd8bhg1tmn5pikdw foreign key (recipient_user_id) references users;
alter table hotel_details add constraint FKfv1jny6gh5bssic2h82f351fj foreign key (place_id) references places;
alter table hotel_facilities add constraint FKe6vsqle07f6gsblrit54260h1 foreign key (hotel_detail_id) references hotel_details;
alter table hotel_languages add constraint FK65k6wr5jfhoy7gkuqpb65hm0i foreign key (hotel_detail_id) references hotel_details;
alter table hotel_payment_methods add constraint FK3rqpe1lkyvpm78qvgywrud5cx foreign key (hotel_detail_id) references hotel_details;
alter table hotel_rooms add constraint FKqcf97lno4qdb7b1ullsei1qal foreign key (hotel_detail_id) references hotel_details;
alter table hotel_services add constraint FK2vs8wyl5nbqjit8tl1c83n51o foreign key (hotel_detail_id) references hotel_details;
alter table inventory_reservations add constraint FKgvwoeebgrhoc76wkhsmsgm56l foreign key (booking_id) references bookings;
alter table inventory_reservations add constraint FKarcii8bssh1ob5tfqqukyob4t foreign key (room_id) references hotel_rooms;
alter table invoices add constraint FKb9bhb7xre5v64qvjeholh3qj0 foreign key (booking_id) references bookings;
alter table invoices add constraint FK8tgri3cdapf1bq9ws2cpob359 foreign key (hotel_id) references places;
alter table invoices add constraint FKq6fs19k0gqw3rg0mb87h60h6p foreign key (payment_id) references payments;
alter table invoices add constraint FKbwr4d4vyqf2bkoetxtt8j9dx7 foreign key (user_id) references users;
alter table loyalty_accounts add constraint FKc3jfk2sj1t7ewn9un7nkr49m1 foreign key (user_id) references users;
alter table loyalty_points_redemptions add constraint FKknaohrh6a64vecnw76mym976a foreign key (booking_id) references bookings;
alter table loyalty_points_redemptions add constraint FK56996mmiskq27b96jjfa8vu6 foreign key (customer_id) references users;
alter table loyalty_points_redemptions add constraint FKshhenvxh2v3fpy159gwaaal21 foreign key (loyalty_account_id) references loyalty_accounts;
alter table loyalty_points_redemptions add constraint FKnfxxufotmlcumfmb7hvi82ufc foreign key (policy_id) references loyalty_redemption_policies;
alter table loyalty_points_transactions add constraint FKjmn7wm4ydbwlgn99jnsu1iaog foreign key (account_id) references loyalty_accounts;
alter table membership_tier_history add constraint FKtle03ulw4u2stje7wfknpc6sv foreign key (membership_id) references customer_memberships;
alter table messages add constraint FKt492th6wsovh1nush5yl5jj8e foreign key (conversation_id) references conversations;
alter table messages add constraint FKk4mpqp6gfuaelpcamqv01brkr foreign key (sender_user_id) references users;
alter table notifications add constraint FKt8ievafor22iuvg5sd4p7lhbk foreign key (recipient_user_id) references users;
alter table partner_activity_logs add constraint FK68dxfxca4asswow8ev26ub1ay foreign key (actor_user_id) references users;
alter table partner_activity_logs add constraint FKq0ime32lx1tv8uxujhw5ct2ku foreign key (partner_profile_id) references partner_profiles;
alter table partner_payout_accounts add constraint FK7cvnxkokkjjsl7hs74pdrnlgv foreign key (partner_profile_id) references partner_profiles;
alter table partner_profiles add constraint FK7jlcw928recan2531mok15yns foreign key (approved_by) references users;
alter table partner_profiles add constraint FK7r7i6kc4t5076ubn78g0jcf42 foreign key (user_id) references users;
alter table partner_settings add constraint FKghwvxkbaw8bt9ic66faekvln9 foreign key (partner_profile_id) references partner_profiles;
alter table partner_team_members add constraint FK16u0pr15inl9tnadq40dn3pmj foreign key (partner_profile_id) references partner_profiles;
alter table partner_team_members add constraint FKsi0m5kcimdl8vu61sjujt4gf1 foreign key (user_id) references users;
alter table payment_session_events add constraint FKn1weaeefdkkdor7ojgqrr355f foreign key (payment_session_id) references payment_sessions;
alter table payment_sessions add constraint FKk978an2mije8rhy4k5ltraxn2 foreign key (booking_id) references bookings;
alter table payment_sessions add constraint FKm3obfwiyi0444c2yc1eujledp foreign key (payment_id) references payments;
alter table payments add constraint FKc52o2b1jkxttngufqp3t7jr3h foreign key (booking_id) references bookings;
alter table place_amenities add constraint FKci1j8jehbxm5653xjreyk0apg foreign key (amenity_id) references amenities;
alter table place_amenities add constraint FKnco1vtybl6usityi8k915w8eo foreign key (place_id) references places;
alter table place_images add constraint FKfaf8mjrs1svk7fgqxufaajmiq foreign key (place_id) references places;
alter table place_metadata add constraint FKang1jwthh32rh3b1voayh16bi foreign key (place_id) references places;
alter table place_metadata_seasons add constraint FKhp7jb30o0jakww16c1q7qr2e5 foreign key (metadata_id) references place_metadata;
alter table place_metadata_travel_styles add constraint FK1mm96yyj5xwgij00v2hce02g8 foreign key (metadata_id) references place_metadata;
alter table place_metadata_visit_times add constraint FKsux5w47ob6nlj67a77c17phau foreign key (metadata_id) references place_metadata;
alter table place_metadata_weather_types add constraint FKe6kpgu11qvvy7koq9tm08krs5 foreign key (metadata_id) references place_metadata;
alter table place_opening_hours add constraint FKoi1q9vix2geed8oeccx21soeq foreign key (place_id) references places;
alter table place_tags add constraint FKt6avw4fcmvitq5gnrxxyec3i6 foreign key (place_id) references places;
alter table places add constraint FKh9p4hmfkt0l1rdntp0kiy689r foreign key (administrative_unit_id) references administrative_units;
alter table places add constraint FK35d4smd8hfnaqo403g9o8ebpv foreign key (approved_by_id) references users;
alter table places add constraint FKca17w9kt9f18v0lr91ssmivx5 foreign key (category_id) references categories;
alter table places add constraint FKt5u395u1lpaabeikbk3lbbvud foreign key (created_by_id) references users;
alter table places add constraint FKjg7finttedwm4vsgsof6en7rg foreign key (owner_partner_profile_id) references partner_profiles;
alter table places add constraint FKphstebuxneu52vtofpll9a5gt foreign key (owner_user_id) references users;
alter table places add constraint FKllbw1umwrymaqe280elko2s8r foreign key (subcategory_id) references categories;
alter table rate_plan_occupancy_prices add constraint FKelki6f8ewe98ot6fdg8847y6e foreign key (rate_plan_id) references rate_plans;
alter table rate_plans add constraint FKcy1d7oam9rsyo8lbjov55wloh foreign key (room_id) references hotel_rooms;
alter table rate_plans add constraint FK74rt9l33rluov8ukcstpk1vrt foreign key (parent_rate_plan_id) references rate_plans;
alter table recently_viewed_places add constraint FKn5ccehhy4ydjrkg5np39psqfb foreign key (place_id) references places;
alter table recently_viewed_places add constraint FKiaxrknenn5llw2bkubrjbj3rr foreign key (user_id) references users;
alter table referral_campaigns add constraint FKbeq0iwyv6dd4rb3ibvmsuerux foreign key (invitee_reward_coupon_definition_id) references coupon_definitions;
alter table referral_campaigns add constraint FKmbj5wyhp1lq3y2dkn1b7oia3q foreign key (inviter_reward_coupon_definition_id) references coupon_definitions;
alter table referral_codes add constraint FKplwuxvljeok3h7tergxtu2hhm foreign key (owner_id) references users;
alter table referral_rewards add constraint FKh08cp7b30qecijmjfv67fbwl4 foreign key (campaign_id) references referral_campaigns;
alter table referral_rewards add constraint FKo2v7s1dyillk9ca2h171br6gu foreign key (invitee_id) references users;
alter table referral_rewards add constraint FKeuvhf93ail6528gs77tg30tp2 foreign key (inviter_id) references users;
alter table referral_rewards add constraint FK34w1360p4u1d8yfo8fk0wxsbo foreign key (referral_code_id) references referral_codes;
alter table reviews add constraint FK28an517hrxtt2bsg93uefugrm foreign key (booking_id) references bookings;
alter table reviews add constraint FKph29qgsctj1qvndduyu2baynw foreign key (partner_replied_by_profile_id) references partner_profiles;
alter table reviews add constraint FKcnnkvk0h9vrih5xqxef7sv2r6 foreign key (place_id) references places;
alter table reviews add constraint FKcgy7qjc1r99dp117y9en6lxye foreign key (user_id) references users;
alter table room_amenities add constraint FKm1qu088g1b1ufhd2mae8fhhmb foreign key (amenity_id) references amenities;
alter table room_amenities add constraint FK3l3dw29at9e43dket120a084y foreign key (room_id) references hotel_rooms;
alter table room_inventory add constraint FKfjkdknp9ygugbklr2tbu2pldn foreign key (room_id) references hotel_rooms;
alter table saved_collection_places add constraint FKoo1o3x97amagad952f7s0ykq2 foreign key (collection_id) references saved_collections;
alter table saved_collection_places add constraint FKgkplsje5tqdas9venw2cr89ee foreign key (place_id) references places;
alter table saved_collections add constraint FKibp0jfsbtm4j4rd4n00uubur0 foreign key (owner_id) references users;
alter table timeline_item add constraint FKh4pou1hd6si680nj8mmtyowls foreign key (place_id) references places;
alter table timeline_item add constraint FK71gn28lklar50k5j26nny0069 foreign key (trip_id) references trip;
alter table travel_credit_accounts add constraint FK94x2abdh4h9b539wrcwetim2w foreign key (user_id) references users;
alter table travel_credit_transactions add constraint FK1vek2e63ngc7176d6ioe6hln foreign key (account_id) references travel_credit_accounts;
alter table travel_wallet_items add constraint FK1laut8ga2a9fxa3ha5oi82qtm foreign key (booking_id) references bookings;
alter table travel_wallet_items add constraint FKhoksyi42u5ccq3vf2esaafqu2 foreign key (invoice_id) references invoices;
alter table travel_wallet_items add constraint FKjbnv4rdbbobbd346e5t0faftd foreign key (trip_plan_id) references trip_plans;
alter table travel_wallet_items add constraint FKakv2atv8bjv117mmbqfpbxvhq foreign key (trip_plan_document_id) references trip_plan_documents;
alter table travel_wallet_items add constraint FK7t1qg313n8mys1clcj53c88w6 foreign key (user_id) references users;
alter table trip add constraint FKd7i66c7muiojrbxvetbx2kobo foreign key (owner_id) references users;
alter table trip_plan_budgets add constraint FKpnnplwi2j3ntdgrl5uaeri15b foreign key (trip_plan_id) references trip_plans;
alter table trip_plan_collaborators add constraint FKdyse96nwrwp0m4qnw17ecqo6j foreign key (trip_plan_id) references trip_plans;
alter table trip_plan_collaborators add constraint FKsl1fx0ipewvc5i3kq9aj07q9j foreign key (user_id) references users;
alter table trip_plan_days add constraint FKkrl5uxst3hbxfa8myajdms8so foreign key (trip_plan_id) references trip_plans;
alter table trip_plan_documents add constraint FKmisyyyr0d96j853i6n3ajmarv foreign key (media_asset_id) references media_assets;
alter table trip_plan_documents add constraint FKs619yvd5l7bo9tnopwiu0hv7e foreign key (trip_plan_day_id) references trip_plan_days;
alter table trip_plan_documents add constraint FKsh1j1xaavjgks8gnglt6ga614 foreign key (trip_plan_item_id) references trip_plan_items;
alter table trip_plan_documents add constraint FKdlt6qgmhylimpwjej58xp04og foreign key (trip_plan_id) references trip_plans;
alter table trip_plan_documents add constraint FKh99wthmhjc8gfmmeh4c1sdhvr foreign key (uploaded_by_user_id) references users;
alter table trip_plan_expenses add constraint FKka6e6v9ha45qpyi5pqpd7jbuk foreign key (paid_by_user_id) references users;
alter table trip_plan_expenses add constraint FK5kqij0kumf9rhwq0fhsrmkr8p foreign key (trip_plan_day_id) references trip_plan_days;
alter table trip_plan_expenses add constraint FKmracxsh7g165odkdcruqn6bdk foreign key (trip_plan_item_id) references trip_plan_items;
alter table trip_plan_expenses add constraint FKknabsdk37b0ug19dh8fj3uju5 foreign key (trip_plan_id) references trip_plans;
alter table trip_plan_items add constraint FKcq19xh21vxim6oo90yhhm6fyh foreign key (place_id) references places;
alter table trip_plan_items add constraint FK423oow9d7io4mxrqc29u2locd foreign key (trip_plan_day_id) references trip_plan_days;
alter table trip_plan_notes add constraint FKsgdntuog6dpfchj1672on8mjl foreign key (author_user_id) references users;
alter table trip_plan_notes add constraint FK5ttwndw1bclu20dhv2sjqsa5f foreign key (trip_plan_day_id) references trip_plan_days;
alter table trip_plan_notes add constraint FKtotpoha2ye9amlarkafeclhfs foreign key (trip_plan_item_id) references trip_plan_items;
alter table trip_plan_notes add constraint FKaj678sd6rw76dko9e1vormoiy foreign key (trip_plan_id) references trip_plans;
alter table trip_plan_packing_items add constraint FK5emqginidla1dl94vs6ju6sgw foreign key (assigned_to_user_id) references users;
alter table trip_plan_packing_items add constraint FK9icbh00pps654knf7dp1ys3su foreign key (trip_plan_id) references trip_plans;
alter table trip_plan_reminders add constraint FKiy98v5e7rvlehntllea0e8si4 foreign key (document_id) references trip_plan_documents;
alter table trip_plan_reminders add constraint FKj1sl5rsd60qioecn7ikpednyw foreign key (trip_plan_day_id) references trip_plan_days;
alter table trip_plan_reminders add constraint FK5bc5vx40bxyay2gq2mwk97umj foreign key (trip_plan_item_id) references trip_plan_items;
alter table trip_plan_reminders add constraint FKi3ohmw1eh13j54xy5w5s6rqec foreign key (trip_plan_id) references trip_plans;
alter table trip_plan_reminders add constraint FKdilnjxheow098doyttli892aj foreign key (user_id) references users;
alter table trip_plans add constraint FKbmly4beva2ojcevvinyll1ccw foreign key (user_id) references users;
alter table user_interest_categories add constraint FKghin1ylx8uw3w78m7nenwah0s foreign key (profile_id) references user_interest_profiles;
alter table user_interest_provinces add constraint FKotxbo1oho4rrpm8rap4ig78la foreign key (profile_id) references user_interest_profiles;
alter table user_interest_tags add constraint FKk7uy5g1lil45tebxkjwilp8rd foreign key (profile_id) references user_interest_profiles;
alter table user_interest_travel_styles add constraint FKgwx6v8k7w15ddy3qsteym23d7 foreign key (profile_id) references user_interest_profiles;
alter table user_interest_weather_types add constraint FK823vh4suok28fr7l94by3un4q foreign key (profile_id) references user_interest_profiles;
alter table wishlist_items add constraint FK96gr68hq7c8l14onb5sqqxb2y foreign key (place_id) references places;
alter table wishlist_items add constraint FKkem9l8vd14pk3cc4elnpl0n00 foreign key (wishlist_id) references wishlists;
alter table wishlists add constraint FK330pyw2el06fn5g28ypyljt16 foreign key (user_id) references users;
